name: Create Infra
on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform install
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.7
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  manual-approval:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Terraform apply need manual approval
        run: echo "Waiting for manual approval to apply changes"

  terraform-apply:
    runs-on: ubuntu-latest
    needs: manual-approval
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
            name: tfplan
            
      - name: Display structure of downloaded files
        run: ls -R your/destination/dir
      
      - name: Unzip tfplan
        run: unzip tfplan.zip

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform install
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.7

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}